# Flowsint — OSINT investigation platform (https://github.com/reconurge/flowsint)
#
# Unlike gitea/mealie/… (native NixOS services inside an nspawn container),
# flowsint ships only as prebuilt Docker images (ghcr.io/reconurge/flowsint-*)
# and its API/celery workers spawn their *own* Docker containers at runtime
# (the OSINT scanners, via the mounted docker.sock). It therefore needs a real
# Docker daemon and is run here with `virtualisation.oci-containers` directly on
# the host — running it inside nspawn would nest Docker two levels deep.
#
# Stack (translated from upstream docker-compose.prod.yml):
#   postgres · redis · neo4j · api · celery · app (frontend, only exposed port)
# Inter-container DNS uses the container names on a dedicated docker network,
# matching the hostnames the images expect (postgres, redis, neo4j, api).
#
# Secrets live in a single sops env-file (see `flowsint-env` below). Create it in
# secrets.yaml with these keys (keep DATABASE_URL's password == POSTGRES_PASSWORD):
#   POSTGRES_PASSWORD=...
#   NEO4J_PASSWORD=...
#   NEO4J_AUTH=neo4j/<same NEO4J_PASSWORD>
#   AUTH_SECRET=...                          # openssl rand -hex 32
#   MASTER_VAULT_KEY_V1=base64:...           # python3 -c "import os,base64;print('base64:'+base64.b64encode(os.urandom(32)).decode())"
#   DATABASE_URL=postgresql://flowsint:<POSTGRES_PASSWORD>@postgres:5432/flowsint
{
  config,
  pkgs,
  lib,
  ...
}: let
  domain = config.var.domain;
  version = "latest";
  apiImage = "ghcr.io/reconurge/flowsint-api:${version}";
  appImage = "ghcr.io/reconurge/flowsint-app:${version}";
  network = "flowsint_network_prod";
  envFile = config.sops.secrets.flowsint-env.path;

  # systemd unit names generated by oci-containers (docker backend).
  containerUnits = map (n: "docker-${n}.service") [
    "postgres"
    "redis"
    "neo4j"
    "api"
    "celery"
    "app"
  ];
in {
  sops.secrets.flowsint-env.mode = "0400";

  virtualisation.docker.enable = true;
  virtualisation.oci-containers.backend = "docker";

  # oci-containers (unlike podman) does not auto-create user-defined networks.
  systemd.services.init-flowsint-network = {
    description = "Create the flowsint docker network";
    after = ["docker.service" "docker.socket"];
    requires = ["docker.service"];
    before = containerUnits;
    requiredBy = containerUnits;
    serviceConfig.Type = "oneshot";
    serviceConfig.RemainAfterExit = true;
    script = ''
      ${pkgs.docker}/bin/docker network inspect ${network} >/dev/null 2>&1 \
        || ${pkgs.docker}/bin/docker network create ${network}
    '';
  };

  virtualisation.oci-containers.containers = {
    postgres = {
      image = "postgres:15-alpine";
      environment = {
        POSTGRES_USER = "flowsint";
        POSTGRES_DB = "flowsint";
      };
      environmentFiles = [envFile];
      volumes = ["pg_data_prod:/var/lib/postgresql/data"];
      extraOptions = ["--network=${network}"];
    };

    redis = {
      image = "redis:7-alpine";
      extraOptions = ["--network=${network}"];
    };

    neo4j = {
      image = "neo4j:5";
      environment = {
        NEO4J_PLUGINS = ''["apoc"]'';
        NEO4J_apoc_export_file_enabled = "true";
        NEO4J_apoc_import_file_enabled = "true";
        NEO4J_apoc_import_file_use__neo4j__config = "true";
      };
      environmentFiles = [envFile]; # provides NEO4J_AUTH
      volumes = [
        "neo4j_data_prod:/data"
        "neo4j_logs_prod:/logs"
        "neo4j_import_prod:/var/lib/neo4j/import"
        "neo4j_plugins_prod:/plugins"
      ];
      extraOptions = ["--network=${network}"];
    };

    api = {
      image = apiImage;
      dependsOn = ["postgres" "redis" "neo4j"];
      environment = {
        NEO4J_URI_BOLT = "bolt://neo4j:7687";
        NEO4J_USERNAME = "neo4j";
        REDIS_URL = "redis://redis:6379/0";
      };
      environmentFiles = [envFile]; # DATABASE_URL, NEO4J_PASSWORD, AUTH_SECRET, MASTER_VAULT_KEY_V1
      # flowsint spawns scanner containers through the host docker daemon.
      volumes = ["/var/run/docker.sock:/var/run/docker.sock:ro"];
      extraOptions = ["--network=${network}"];
    };

    celery = {
      image = apiImage;
      dependsOn = ["postgres" "redis" "neo4j" "api"];
      cmd = [
        "celery"
        "-A"
        "flowsint_core.core.celery"
        "worker"
        "--loglevel=info"
        "--pool=threads"
        "--concurrency=10"
      ];
      environment = {
        NEO4J_URI_BOLT = "bolt://neo4j:7687";
        NEO4J_USERNAME = "neo4j";
        REDIS_URL = "redis://redis:6379/0";
        SKIP_MIGRATIONS = "true";
      };
      environmentFiles = [envFile];
      volumes = ["/var/run/docker.sock:/var/run/docker.sock:ro"];
      extraOptions = ["--network=${network}"];
    };

    app = {
      image = appImage;
      dependsOn = ["api"];
      # Only network-facing port: serves the UI and proxies /api/ to the api
      # container. Bound to localhost; cloudflared (host) reverse-proxies it.
      ports = ["127.0.0.1:5173:8080"];
      extraOptions = ["--network=${network}"];
    };
  };

  services.cloudflared.tunnels."${config.var.tunnelId}".ingress."flowsint.${domain}" = "http://localhost:5173";
}
